phpbbstudio_dice:
    path: /dice
    defaults:
        _controller: phpbbstudio.dice.controller.main:page

phpbbstudio_dice_add:
    path: /dice/add/f{forum_id}/t{topic_id}/p{post_id}/a{poster_id}/{hash}
    defaults:
        _controller: phpbbstudio.dice.controller.main:add
    requirements:
        forum_id: \d+
        topic_id: \d+
        post_id: \d+
        poster_id: \d+

phpbbstudio_dice_edit:
    path: /dice/edit/{roll_id}
    defaults:
        _controller: phpbbstudio.dice.controller.main:edit
        roll_id: 0
    requirements:
        roll_id: \d+

phpbbstudio_dice_del:
    path: /dice/del/{roll_id}
    defaults:
        _controller: phpbbstudio.dice.controller.main:delete
        roll_id: 0
    requirements:
        roll_id: \d+
